require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/opinions', type: :request do
  # Opinion. As you add validations to Opinion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Opinion.create! valid_attributes
      get opinions_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      opinion = Opinion.create! valid_attributes
      get opinion_url(opinion)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_opinion_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      opinion = Opinion.create! valid_attributes
      get edit_opinion_url(opinion)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Opinion' do
        expect do
          post opinions_url, params: { opinion: valid_attributes }
        end.to change(Opinion, :count).by(1)
      end

      it 'redirects to the created opinion' do
        post opinions_url, params: { opinion: valid_attributes }
        expect(response).to redirect_to(opinion_url(Opinion.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Opinion' do
        expect do
          post opinions_url, params: { opinion: invalid_attributes }
        end.to change(Opinion, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post opinions_url, params: { opinion: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested opinion' do
        opinion = Opinion.create! valid_attributes
        patch opinion_url(opinion), params: { opinion: new_attributes }
        opinion.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the opinion' do
        opinion = Opinion.create! valid_attributes
        patch opinion_url(opinion), params: { opinion: new_attributes }
        opinion.reload
        expect(response).to redirect_to(opinion_url(opinion))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        opinion = Opinion.create! valid_attributes
        patch opinion_url(opinion), params: { opinion: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested opinion' do
      opinion = Opinion.create! valid_attributes
      expect do
        delete opinion_url(opinion)
      end.to change(Opinion, :count).by(-1)
    end

    it 'redirects to the opinions list' do
      opinion = Opinion.create! valid_attributes
      delete opinion_url(opinion)
      expect(response).to redirect_to(opinions_url)
    end
  end
end
